definitions:
  common.Response:
    properties:
      code:
        type: integer
      data: {}
      message:
        type: string
    type: object
info:
  contact: {}
paths:
  /api/health:
    get:
      description: HealthCheck status is ready of service
      operationId: HealthCheck
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/common.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/common.Response'
      summary: HealthCheck
      tags:
      - HealthCheck
swagger: "2.0"
