definitions:
  common.Response:
    properties:
      code:
        description: custom code response from the server
        type: integer
      data:
        description: data response from the server
      message:
        description: custom message response from the server
        type: string
    type: object
  github_com_coregate_tickets-app_pkg_auth.CreateUser:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        type: string
      username:
        type: string
    required:
    - email
    - name
    - password
    - username
    type: object
info:
  contact: {}
paths:
  /api/auth/register:
    post:
      consumes:
      - application/json
      description: Register new user
      operationId: Register
      parameters:
      - description: User data
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/github_com_coregate_tickets-app_pkg_auth.CreateUser'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/common.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/common.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/common.Response'
      summary: Register
      tags:
      - Auth
  /api/health:
    get:
      description: HealthCheck status is ready of service
      operationId: HealthCheck
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/common.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/common.Response'
      summary: HealthCheck
      tags:
      - HealthCheck
swagger: "2.0"
